morse_code={}
morse_code["A"] = "._"
morse_code["B"] = "_..."
morse_code["C"] = "_._."
morse_code["D"] = "_.."
morse_code["E"] = "."
morse_code["F"] = ".._."
morse_code["G"] = "__."
morse_code["H"] = "...."
morse_code["I"] = ".."
morse_code["J"] = ".___"
morse_code["K"] = "_._"
morse_code["L"] = "._.."
morse_code["M"] = "__"
morse_code["N"] = "_."
morse_code["O"] = "___"
morse_code["P"] = "._._."
morse_code["Q"] = "__._"
morse_code["R"] = "._."
morse_code["S"] = "..."
morse_code["T"] = "_"
morse_code["U"] = ".._"
morse_code["V"] = "..._"
morse_code["W"] = ".__"
morse_code["X"] = "_._"
morse_code["Y"] = "_.__"
morse_code["Z"] = "__.."
morse_code[" "] = " | "


phrase = "DIA VAGYOK ES SZERETEK PROGRAMOZNI"
print(''.join([morse_code.get(i,i) for i in phrase]))
